version: '3'

services:
    mongodb:
        image: mongo
        volumes:
            - ./temp:/data/db
        restart: always
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=example
            - MONGO_INITDB_DATABASE=test
        
    springboot:
        depends_on:
            - mongodb
        build: .
        links:
            - mongodb:mongodb
        ports:
            - 8080:8080
        restart: always
        